# This workflow will build the service and test Docker images for HyBIG, then
# run the Python `unittest` suite within a test Docker container, reporting
# test results and code coverage as artefacts. It will be called by the
# workflow that run tests against new PRs and as a first step in the workflow
# that publishes new Docker images.
name: Run Python tests

on:
  workflow_call

jobs:
  build_and_test_service:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout harmony-browse-image-generator repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Build service image
        run: ./bin/build-image

      - name: Build test image
        run: ./bin/build-test

      - name: Run test image
        run: ./bin/run-test

      - name: Archive test results and coverage
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/**/*
